#! /usr/bin/env sh

crux_gnulinux() {
	mkbootstrap "crux_gnulinux" "$DIR/bootstrap"					\
											\
		--ports "$PWD/cruxmedia/crux/core"					\
											\
		"acl"			"iana-etc"		"procps"		\
		"attr"			"inetutils"		"psmisc"		\
		"bash"			"iproute2"		"rc"			\
		"bzip2"			"iptables"		"readline"		\
		"ca-certificates"	"kbd"			"sed"			\
		"coreutils"		"kmod"			"shadow"		\
		"dash"			"less"			"start-stop-daemon"	\
		"dcron"			"libcap"		"sysklogd"		\
		"dhcpcd"		"libdevmapper"		"sysvinit"		\
		"e2fsprogs"		"libgmp"		"tar"			\
		"eudev"			"libmpfr"		"tzdata"		\
		"file"			"libpcre"		"util-linux"		\
		"filesystem"		"linux-pam"		"vim"			\
		"findutils"		"lzo"			"wget"			\
		"gawk"			"ncurses"		"which"			\
		"glibc"			"openssh"		"xz"			\
		"grep"			"openssl"		"zlib"			\
		"gzip"			"pkgutils"

	install -d -m 0700 "$DIR/bootstrap/root/.ssh"

	if cd "$HOME/.ssh"; then
		for key in *".pub"; do
			cat "$key" >> "$DIR/bootstrap/root/.ssh/authorized_keys"
		done
		cd "$OLDPWD"
	fi

	sed -i "s/SERVICES=.*/SERVICES=(lo net crond sshd)/g" "$DIR/bootstrap/etc/rc.conf"

	exportroot "$DIR/bootstrap" > "$PWD/crux_gnulinux-embedded.rootfs"
}

main() {
	DIR="$(mktemp -d -p $PWD)"

	for dir in bootstrap; do
		mkdir "$DIR/$dir" 2>/dev/null
	done

	crux_gnulinux "$@"
}

main "$@"
