#! /usr/bin/env sh

crux_gnulinux() {
	importroot "$DIR/initramfs" < "$PWD/crux_gnulinux-embedded.rootfs"

	mkbootstrap "crux_gnulinux" "$DIR/initramfs"					\
											\
		--ports "$PWD/cruxports"						\
											\
		"htop"		"kexec-tools"	"linux"

	echo "#! /sbin/init" > "$DIR/initramfs/init"
	chmod +x "$DIR/initramfs/init"

	mkdir "$DIR/initramfs/root/.ssh"
	for key in "$HOME/.ssh/"*".pub"; do
		cat "$key" >> "$DIR/initramfs/root/.ssh/authorized_keys"
	done

	sed -i "s/SERVICES.*/SERVICES=(lo net crond sshd)/g" "$DIR/initramfs/etc/rc.conf"

	exportroot "$DIR/initramfs" > "$PWD/crux_gnulinux-initrd.rootfs"

	mkinitramfs "$DIR/initramfs"							\
											\
		--standalone								\
											\
		--output "$DIR/initramfs.img"

	xz --check="crc32" --keep --threads=0 "$DIR/initramfs.img"

	install -D "$DIR/initramfs/lib/modules/"*"/vmlinuz" "$DIR/bootimage/boot/vmlinuz"
	install -D "$DIR/initramfs.img.xz" "$DIR/bootimage/boot/initrd"

	mkbootisofs "$DIR/bootimage"							\
											\
		--legacy-boot "grub2"							\
											\
		--efi "grub2"								\
											\
		--output "$DIR/install.iso"
}

main() {
	DIR="$(mktemp -d -p $PWD)"

	for dir in initramfs bootimage; do
		mkdir "$DIR/$dir"
	done

	crux_gnulinux "$@"
}

main "$@"
