#! /usr/bin/env sh

crux_gnulinux() {
	importroot "$DIR/bootstrap" < "$PWD/crux_gnulinux-embedded.rootfs"

	mkbootstrap "crux_gnulinux" "$DIR/bootstrap"					\
											\
		--ports "$PWD/cruxports"						\
											\
		"linux"

	mkinitramfs "$DIR/initramfs"							\
											\
		--output "$DIR/initramfs.img"

	xz --check="crc32" --keep --threads=0 "$DIR/initramfs.img"

	install -D "$DIR/bootstrap/boot/vmlinuz-"* "$DIR/bootimage/boot/vmlinuz"
	install -D "$DIR/initramfs.img.xz" "$DIR/bootimage/boot/initrd"

	mkbootisofs "$DIR/bootimage"							\
											\
		--legacy-boot "syslinux"						\
											\
		--efi "grub2"								\
											\
		--overlay "$DIR/bootstrap"						\
											\
		--cpio									\
											\
		--output "$DIR/install.iso"
}

main() {
	DIR="$(mktemp -d -p $PWD)"

	for dir in bootstrap initramfs bootimage; do
		mkdir "$DIR/$dir"
	done

	crux_gnulinux "$@"
}

main "$@"
